export const JOB_TITLES = [
  // Software Development & Engineering
  "Software Engineer",
  "Software Developer",
  "Backend Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "Android Developer",
  "iOS Developer",
  "Mobile Developer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Blockchain Engineer",
  "Robotics Engineer",
  "Software Integration Engineer",
  "Web Developer",
  "WordPress Developer",
  "Front-End Designer",
  "Web Analytics Developer",
  "Senior Software Engineer",
  "Junior Software Developer",
  "Principal Software Engineer",
  "Software Architect",

  // Data, AI & Machine Learning
  "Data Scientist",
  "Data Engineer",
  "Data Architect",
  "Data Analyst",
  "Database Administrator (DBA)",
  "Big Data Engineer",
  "BI Developer",
  "Machine Learning Engineer",
  "AI Engineer",
  "AI Researcher",
  "AI Architect",

  // DevOps, Cloud & Infrastructure
  "DevOps Engineer",
  "Cloud Architect",
  "Cloud Engineer",
  "Site Reliability Engineer (SRE)",
  "Systems Engineer",
  "Systems Administrator",
  "Network Engineer",
  "Network Architect",
  "Build and Release Engineer",
  "Security Engineer",
  "Information Security Specialist",

  // Design & User Experience
  "UX Designer",
  "UI Designer",
  "Product Designer",
  "UX Researcher",
  "Interaction Designer",
  "Graphic Designer",

  // Management, Strategy & Product
  "Product Manager",
  "Program Manager",
  "Project Manager",
  "Technical Project Manager",
  "Engineering Manager",
  "Team Lead",
  "Technical Lead",
  "Scrum Master",
  "QA Engineer",
  "QA Tester",
  "Quality Assurance Engineer",

  // IT Support & Operations
  "IT Support Specialist",
  "Technical Support Engineer",
  "Help Desk Technician",
  "Desktop Support Specialist",
  "Customer Support Administrator",

  // Marketing & Growth
  "Marketing Technologist",
  "SEO Specialist",
  "Digital Marketing Manager",
  "Growth Hacker",
];
